spring:
  application:
    name: mini-portfolio-api

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: jskt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true